cache: bundler
language: ruby
rvm:
 - 2.5.8
 - 2.6.6
 - 2.7.2
 - ruby-head
before_install:
  - gem update --system
  - gem install bundler
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 1.9.3
